services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: cachesrv
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "cachesrv"]
      start_period: 2s
      interval: 1s
      retries: 5
      timeout: 1s
    networks:
      - cache-local

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/minio/health/live"]
      start_period: 2s
      interval: 1s
      retries: 5
      timeout: 1s
    networks:
      - cache-local

  cache-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "12345:12345" # Management API
      - "54321:54321" # Deploy/WS Port
    volumes:
      - ./server.conf:/app/cache-server.conf
      - cache_storage:/app/binary-caches
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:12345/api/v1/version"]
      start_period: 2s
      interval: 1s
      retries: 5
      timeout: 1s
    networks:
      - cache-local
    command: ["listen", "-f"]

  cache-test-node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "23455:23455" # Cache test port
    volumes:
      - ./server.conf:/app/cache-server.conf:ro
      - cache_storage:/app/binary-caches
    depends_on:
      cache-server:
        condition: service_started
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider http://localhost:23455/version 2>&1 | grep -qE '200 OK|401 Unauthorized'"]
      start_period: 2s
      interval: 1s
      retries: 5
      timeout: 1s
    networks:
      - cache-local
    command: ["cache", "start", "test", "-f"]

networks:
  cache-local:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  cache_storage:
