services:
  db:
    image: postgres
    restart: always
    environment:
      postgres_user: postgres
      postgres_password: postgres
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["cmd", "pg_isready", "-u", "postgres", "-d", "cachesrv"]
      start_period: 1s
      interval: 0.5s
      retries: 5
      timeout: 0.5s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
