version: "3"

vars:
  BINARY_DIR: ./bin
  APP_NAME: cache-server
  CODE_DIR: ./src
  PACKAGE: "github.com/killi1812/go-cache-server"

tasks:
  default:
    cmds:
      - task: list-tools
    silent: false

  dev:
    description: build project binary for development
    cmds:
      - task: build-int
        vars:
          BUILD: "dev"
    silent: true

  build-int:
    description: build project binary
    vars:
      VERSION:
        sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//'
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BUILD_TIMESTAMP:
        sh: date '+%Y-%m-%dT%H:%M:%S'
      LDFLAGS: "-X '{{.PACKAGE}}/app.Build={{.BUILD}}' -X '{{.PACKAGE}}/app.Version={{.VERSION}}' -X '{{.PACKAGE}}/app.CommitHash={{.COMMIT_HASH}}' -X '{{.PACKAGE}}/app.BuildTimestamp={{.BUILD_TIMESTAMP}}'"
    cmds:
      - cmd: "echo 'Build info\n\tBuild:\t\t{{.BUILD}}\n\tVersion:\t{{.VERSION}}\n\tCommit:\t\t{{.COMMIT_HASH}}\n\tTime Stamp:\t{{.BUILD_TIMESTAMP}}'"
      - cmd: mkdir -p {{.BINARY_DIR}}
      - cmd: go build -C {{.CODE_DIR}} -ldflags="{{.LDFLAGS}}" -v -o ../{{.BINARY_DIR}}/{{.APP_NAME}}
    silent: true
    internal: true

  build:
    description: build a project
    vars:
      BUILD: "prod"
    cmds:
      - task: build-int
        vars:
          BUILD: "{{.BUILD}}"
    silent: true

  install:
    description: install project as your local binary
    cmds:
      # TODO: Implement installation
      - task: build
    # TODO: Implement installation
    silent: true

  test:
    description: run project tests
    # TODO: Implement
    silent: true

  coverage:
    description: creates project coverage file
    # TODO: Implement
    silent: true

  list-tools:
    cmds:
      - go version
      - gcc --version
      - task --version
    silent: true
