// Package management Code generated by swaggo/swag. DO NOT EDIT
package management

import "github.com/swaggo/swag"

const docTemplatemanagement = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cache/{name}": {
            "get": {
                "description": "Get detailed information about a binary cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cache info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/{name}/multipart-nar": {
            "post": {
                "description": "Initialize a multipart upload for a NAR file.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Create multipart NAR upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Compression method (xz or zst)",
                        "name": "compression",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/{name}/multipart-nar/{narUuid}": {
            "post": {
                "description": "Get the direct upload URL for a multipart NAR upload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Redirect to upload URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NAR UUID",
                        "name": "narUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/{name}/multipart-nar/{narUuid}/abort": {
            "post": {
                "description": "Abort a multipart upload and clean up placeholder files.",
                "tags": [
                    "cache"
                ],
                "summary": "Abort multipart NAR upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NAR UUID",
                        "name": "narUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cache/{name}/multipart-nar/{narUuid}/complete": {
            "post": {
                "description": "Finalize a multipart upload and create the store path entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Complete multipart NAR upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NAR UUID",
                        "name": "narUuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Completion details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CompletedMultipartUpload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/{name}/narinfo": {
            "post": {
                "description": "Returns a list of hashes from the input that are missing in the cache.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get missing narinfo hashes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Hashes to check",
                        "name": "hashes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/activate": {
            "post": {
                "description": "Activate deployments for multiple agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Activate deployment",
                "parameters": [
                    {
                        "description": "Activation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ActivateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Deployment"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/agent/{workspace}/{name}": {
            "get": {
                "description": "Get detailed information about an agent in a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Get agent info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Agent"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new agent in a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Create agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Agent"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an agent from a workspace.",
                "tags": [
                    "agent"
                ],
                "summary": "Delete agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/deployment/{workspace}": {
            "get": {
                "description": "Get detailed information about a deployment by UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Get deployment info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment UUID",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/deployment/{workspace}/{name}": {
            "get": {
                "description": "List all deployments for a specific agent in a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Get deployments for agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Deployment"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new deployment for an agent.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Create deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/deployment/{workspace}/{name}/{index}": {
            "get": {
                "description": "Get a specific deployment for an agent by its index.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "Get deployment by index",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deployment Index",
                        "name": "index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/log/": {
            "get": {
                "description": "Stream real-time logs from the agent during deployment.",
                "tags": [
                    "deployment"
                ],
                "summary": "Deployment log WebSocket",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        },
        "/deploy/workspace": {
            "post": {
                "description": "Create a new workspace associated with a binary cache.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Create workspace",
                "parameters": [
                    {
                        "description": "Workspace details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.WorkspaceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Workspace"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/workspace/{workspace}": {
            "get": {
                "description": "Get detailed information about a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get workspace info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Workspace"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a workspace by name.",
                "tags": [
                    "workspace"
                ],
                "summary": "Delete workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/workspace/{workspace}/agents": {
            "get": {
                "description": "List all agents in a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "List agents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace Name",
                        "name": "workspace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Agent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/ws": {
            "get": {
                "description": "Long-lived WebSocket connection for agents to receive deployment commands.",
                "tags": [
                    "deployment"
                ],
                "summary": "Agent WebSocket registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent Name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent Token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy/ws-deployment": {
            "get": {
                "description": "Channel for agents to report deployment completion.",
                "tags": [
                    "deployment"
                ],
                "summary": "Deployment status WebSocket",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ActivateRequest": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "api.CompletedMultipartUpload": {
            "type": "object",
            "properties": {
                "narInfoCreate": {
                    "$ref": "#/definitions/api.NarInfoCreate"
                }
            }
        },
        "api.NarInfoCreate": {
            "type": "object",
            "properties": {
                "cDeriver": {
                    "type": "string"
                },
                "cFileHash": {
                    "type": "string"
                },
                "cFileSize": {
                    "type": "integer"
                },
                "cNarHash": {
                    "type": "string"
                },
                "cNarSize": {
                    "type": "integer"
                },
                "cReferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cSig": {
                    "type": "string"
                },
                "cStoreHash": {
                    "type": "string"
                },
                "cStoreSuffix": {
                    "type": "string"
                }
            }
        },
        "api.WorkspaceRequest": {
            "type": "object",
            "required": [
                "cacheName",
                "name"
            ],
            "properties": {
                "cacheName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Agent": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "integer"
                }
            }
        },
        "model.BinaryCache": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/model.BinaryCacheAccess"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "publicKey": {
                    "type": "string"
                },
                "retention": {
                    "type": "integer"
                },
                "store_paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StorePath"
                    }
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Workspace"
                    }
                }
            }
        },
        "model.BinaryCacheAccess": {
            "type": "string",
            "enum": [
                "private",
                "public"
            ],
            "x-enum-varnames": [
                "Private",
                "Public"
            ]
        },
        "model.Deployment": {
            "type": "object",
            "properties": {
                "agent": {
                    "$ref": "#/definitions/model.Agent"
                },
                "agentId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.DeploymentStatus"
                },
                "storePath": {
                    "type": "string"
                }
            }
        },
        "model.DeploymentStatus": {
            "type": "string",
            "enum": [
                "pending",
                "in_progress",
                "success",
                "failed"
            ],
            "x-enum-varnames": [
                "DeploymentPending",
                "DeploymentInProgress",
                "DeploymentSuccess",
                "DeploymentFailed"
            ]
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "not found"
                }
            }
        },
        "model.StorePath": {
            "type": "object",
            "properties": {
                "binaryCacheId": {
                    "description": "BinaryCacheId uint         ` + "`" + `json:\"binarycacheId\"` + "`" + `\nBinaryCache   *BinaryCache ` + "`" + `json:\"-\"` + "`" + `",
                    "type": "integer"
                },
                "deriver": {
                    "type": "string"
                },
                "fileHash": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "narHash": {
                    "type": "string"
                },
                "narSize": {
                    "type": "integer"
                },
                "references": {
                    "description": "Stored as a string (serialized)",
                    "type": "string"
                },
                "storeHash": {
                    "type": "string"
                },
                "storeSuffix": {
                    "type": "string"
                }
            }
        },
        "model.Workspace": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Agent"
                    }
                },
                "binary_cache": {
                    "$ref": "#/definitions/model.BinaryCache"
                },
                "binary_cache_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfomanagement holds exported Swagger Info so clients can modify it
var SwaggerInfomanagement = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Management API",
	Description:      "API for managing binary caches, workspaces, and agents.",
	InfoInstanceName: "management",
	SwaggerTemplate:  docTemplatemanagement,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfomanagement.InstanceName(), SwaggerInfomanagement)
}
