// Package cache Code generated by swaggo/swag. DO NOT EDIT
package cache

import "github.com/swaggo/swag"

const docTemplatecache = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/log/{deriver}": {
            "get": {
                "description": "Get the build logs for a particular deriver.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Get build logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full name of the deriver",
                        "name": "deriver",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "log content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/nar/{filename}": {
            "get": {
                "description": "Download a NAR file from the cache.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Download NAR file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NAR filename (e.g. hash.nar.xz)",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/nix-cache-info": {
            "get": {
                "description": "Get information about the nix store configuration.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Get nix-cache-info",
                "responses": {
                    "200": {
                        "description": "StoreDir: /nix/store...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{filename}": {
            "put": {
                "description": "Upload raw NAR data for a given filename (usually hash).",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Upload NAR data (Direct)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filename or Hash",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{storeHash}": {
            "get": {
                "description": "Get metadata (.narinfo) or file listing (.ls) for a store hash.\n- .narinfo: Text file containing store path metadata (NAR hash, size, references, signature).\n- .ls: JSON file containing the internal file listing of the NAR.",
                "produces": [
                    "text/plain",
                    "application/json"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Get .narinfo or .ls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store hash with extension (.narinfo or .ls)",
                        "name": "storeHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File listing JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Metadata or listing not found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "not found"
                }
            }
        }
    }
}`

// SwaggerInfocache holds exported Swagger Info so clients can modify it
var SwaggerInfocache = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "cache",
	SwaggerTemplate:  docTemplatecache,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocache.InstanceName(), SwaggerInfocache)
}
