// Package cache Code generated by swaggo/swag. DO NOT EDIT
package cache

import "github.com/swaggo/swag"

const docTemplatecache = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nar/{filename}": {
            "get": {
                "description": "Download a NAR file from the cache.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Download NAR file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NAR filename (with or without .nar extension)",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/nix-cache-info": {
            "get": {
                "description": "Get information about the nix store configuration.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Get nix-cache-info",
                "responses": {
                    "200": {
                        "description": "StoreDir: /nix/store...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{narUuid}": {
            "put": {
                "description": "Upload raw NAR data for a given UUID.",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Upload NAR data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "NAR UUID",
                        "name": "narUuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/{storeHash}": {
            "get": {
                "description": "Get metadata (.narinfo) or file listing (.ls) for a store hash.",
                "produces": [
                    "text/plain",
                    "application/json"
                ],
                "tags": [
                    "binary-cache"
                ],
                "summary": "Get .narinfo or .ls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store hash with extension (.narinfo or .ls)",
                        "name": "storeHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ls json",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    }
}`

// SwaggerInfocache holds exported Swagger Info so clients can modify it
var SwaggerInfocache = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Binary Cache API",
	Description:      "API for nix binary cache interactions (narinfo, nar, etc).",
	InfoInstanceName: "cache",
	SwaggerTemplate:  docTemplatecache,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocache.InstanceName(), SwaggerInfocache)
}
