name: deployment

on:
  workflow_call:
    secrets:
      WEBHOOK_SECRET:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: homelab
    steps:
      - name: Trigger Deploy Webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: 'curl -v -X POST -H "X-Api-Key: $WEBHOOK_SECRET" https://webhook.francvok.from.hr/hooks/cache-server'
